version: "2"
services:
  web:
   # build: .
   image: jperump/thenextai:v1.1
   ports:
      - "8080:3000"
   depends_on:
      - "mongodb"
   links:
      - "mongodb"
   volumes:
      - "./webappdata:/opt/app/public/img/users"
   container_name: webapp
  mongodb:
   image: mongo
   ports:
      - "27017:27017"
   container_name: mongodb
   volumes:
      - "./mongodb:/data/db"